### ISSUE TITLE
Data.Bits.Extras.oneBits clashes with Data.Bits.oneBits in GHC 9.2

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/bits#12]
If you try to build `bits` with `base-4.16` (bundled with GHC 9.2), you'll get this error:

```
[1 of 3] Compiling Data.Bits.Extras ( src/Data/Bits/Extras.hs, interpreted )

src/Data/Bits/Extras.hs:210:39: error:
    Ambiguous occurrence ‘oneBits’
    It could refer to
       either ‘Data.Bits.oneBits’,
              imported from ‘Data.Bits’ at src/Data/Bits/Extras.hs:34:1-16
           or ‘Data.Bits.Extras.oneBits’,
              defined at src/Data/Bits/Extras.hs:204:1
    |
210 | srl b n = (b `shiftR` n) .&. rotateR (oneBits `shiftL` n) n
    |                                       ^^^^^^^
```

This is because `Data.Bits` now defines a [function named `oneBits`](https://gitlab.haskell.org/ghc/ghc/-/blob/0a8c14bd5a5438b1d042ad279b8ffff1bc867e7e/libraries/base/Data/Bits.hs#L71-88) as well. It is almost the same as the `oneBits` function defined in `Data.Bits.Extras`, but with one key difference—`Data.Bits`' `oneBits` has a `FiniteBits` constraint, while `Data.Bits.Extras`' `oneBits` has a `Bits` constraint. Note that some functions currently rely on the weaker `Bits` constraint (e.g., `Data.Bits.Extras.srl`), so the two are not interchangeable.

How should we address this? I see two possibilities:

1. Hide `Data.Bits`' `oneBits` when importing it throughout `bits` and continue defining `Data.Bits.Extras`' version separately.
2. Re-export `Data.Bits`' `oneBits` when building with `base-4.16` or later, and on older versions of `base`, define a compatibility shim for `oneBits` with a `FiniteBits` constraint.

I'd personally prefer possibility (2), although that would require a breaking change.

**Comment by RyanGlScott** [comment]
Actually, there's another issue with option (2). Because `Data.Bits`' `oneBits` uses a `FiniteBits` constraint, one cannot use `oneBits :: Integer`. The `bits` library _does_ use this instance, however, in `Data.Bits.Coded.ones`:

https://github.com/ekmett/bits/blob/04fe092832e45f3226baff57e1c56279f24c87a5/src/Data/Bits/Coded.hs#L48-L53

This is, of course, not the only possible way to define `ones`, but it does raise the question of whether option (2) is the best fit for the assumptions that the `bits` library makes.

**Comment by RyanGlScott** [comment]
Thoughts on this, @ekmett?

**Comment by RyanGlScott** [comment]
A third possibility is to rename `bits`' `oneBits` function to something else. Perhaps `unsafeOneBits` to reflect that it cannot safely be used on some `Bits` instances, like `Natural`?

**Comment by RyanGlScott** [comment]
I went ahead and submitted #13, which implements a hybrid of options (2) and (3). Let me know what you think, @ekmett.

**Comment by ekmett** [comment]
Your fix works for me.
